### ISSUE TITLE
Have "." be sorted before recent files (at least in dir mode)

### ISSUE THREAD

**Issue by kootenpv** [pkkm/ido-sort-mtime#1]
Would this be possible? I've been trying myself, but can't figure it out.

**Comment by kootenpv** [comment]
It's still bothering me. I tried solving it but I have no idea how :/

**Comment by pkkm** [comment]
I've added a new variable, `ido-sort-mtime-dot-at-beginning`, in the `next` branch. Could you check if it does what you want?

**Comment by kootenpv** [comment]
Thanks a lot, I really like the idea of the package. It potentially really works great. I had another bug actually, which is why I stopped using it for a bit (I noticed it was solved by disabling this package). I'll make an issue for that.

Since actually, whenever I use dired, I most of the time use it to open it in current directory, that's why I would like the dot at the start :)

So, I checked it out, and I ensured inspection shows:

```
ido-sort-mtime-dot-at-beginning’s value is t

Documentation:
Not documented as a variable.
```

In the sorting though, `.` does not show being first, but rather *third* in my case.

I have verified that the dot `.` is now being considered for sorting (whereas before it was always last if I recall correctly). So, in my case, the dot *is* actually the third one when we sort all directories.

Looking at the code, this seems difficult to explain...

Thanks a lot for the update!

**Comment by pkkm** [comment]
Have you replaced the version from MELPA with the version from the `next` branch? I haven't pushed the new version to MELPA yet because I'd like to first confirm that it resolves this issue.

**Comment by kootenpv** [comment]
Yea, I just replaced the version in package folder. I can see that I have the new variables.

**Comment by pkkm** [comment]
I can't reproduce the issue. After evaluating the following in an unconfigured Emacs 26.0.50:

```elisp
(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-refresh-contents)
(package-install 'ido-sort-mtime)

(package-install 'epl)
(require 'epl)
(require 'url)
(let ((dir (epl-package-directory
            (car (epl-find-installed-packages 'ido-sort-mtime)))))
  (url-copy-file "https://raw.githubusercontent.com/pkkm/ido-sort-mtime/next/ido-sort-mtime.el"
                 (expand-file-name "ido-sort-mtime.el" dir)
                 t)
  (delete-file (expand-file-name "ido-sort-mtime.elc" dir)))

(ido-mode)
(setq ido-sort-mtime-dot-at-beginning t)
;;(setq ido-show-dot-for-dired t)
(ido-sort-mtime-mode)
```

Ido behaves as expected: `.` is always the first entry in dir mode, and also in file mode if I uncomment the second-to-last line. Are you sure you don't have old `ido-sort-mtime.el` or `ido-sort-mtime.elc` files lying around somewhere where Emacs sees them?

**Comment by kootenpv** [comment]
My sincerest apologies! It indeed just works now. It indeed had to do with the `.elc`. I was under the impression that Emacs automatically detects when the .elc is outdated to the .el, and then recompiles. I'm sorry for posting the comments in the first place.....
It's working really nicely. Thanks!

**Comment by pkkm** [comment]
I'll release the new version then. Thanks for the feature request!

**Comment by kootenpv** [comment]
Great, I'll be sure to pick it up officially then :)

**Comment by kootenpv** [comment]
I've missed here that I think we only want "." to be first in dir mode? Not in file mode :/

**Comment by pkkm** [comment]
If you set `ido-show-dot-for-dired` to `nil`, it shouldn't be shown in file mode at all.

**Comment by kootenpv** [comment]
Awesome! It now indeed works exactly how I personally like it! I hope others will find what they want too!
