### ISSUE TITLE
`ido-sort-mtime` makes typing "C-x C-f /ssh:" hang

### ISSUE THREAD

**Issue by kootenpv** [pkkm/ido-sort-mtime#2]
I made an issue on reddit, and later realized that when I removed this package it was solved.

https://www.reddit.com/r/emacs/comments/6guu3s/tramp_is_confused_typing_ssh_gets_me_stuck_trying/

Really sad to had to let it go :(

**Comment by pkkm** [comment]
I can't reproduce the issue on Emacs 24.5.1 on Debian. Which Emacs version are you using?

**Comment by kootenpv** [comment]
Emacs 26.0.50. Interestingly with this new branch, and after some time has passed...... it now doesn't seem to be happening anymore so I'm quite happy!

Maybe it was perspective or projectile that were creating a weird state.

**Comment by kootenpv** [comment]
I personally cannot reproduce it even, so I'm very glad. Perhaps the next person will have a better clue what was wrong in the setup.

Thanks for the support!
