### ISSUE TITLE
Slow and thus "hangs" for big folders

### ISSUE THREAD

**Issue by kootenpv** [pkkm/ido-sort-mtime#3]
In my case, 2000 files is already considered big. Maybe it would be possible to set a cutoff for when not to sort, or maybe caching could be done? I don't know... perhaps there is a prettier solution out there?

**Comment by pkkm** [comment]
I can't think of a solution better than setting a cutoff, so I've introduced the variable `ido-sort-mtime-limit` in the newest version.
